spring:
  application:
    name: api

server:
  port: 8080

security:
 jwt:
  secret: 01234567890123456789012345678901
  issuer: btg-api-local
  expiration-minutes: 60

aws:
  dynamodb:
    accessKey: test
    secretKey: test
    endpoint: http://localhost:8000
    region: localhost
